version: "3.8"

services:
  glimpse:
    container_name: glimpse
    build:
      context: ./
      dockerfile: dev.Dockerfile
    environment:
      TMDB_API_KEY: ${TMDB_API_KEY}
      TMDB_ACCESS_TOKEN: ${TMDB_ACCESS_TOKEN}
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
