version: "3"

services:
  glimpse:
    container_name: glimpse
    build:
      context: ./
      dockerfile: prod.Dockerfile
      args:
        TMDB_API_KEY: ${TMDB_API_KEY}
        TMDB_ACCESS_TOKEN: ${TMDB_ACCESS_TOKEN}
    restart: always
    ports:
      - 3000:3000
