name: Backfill and Revalidate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2,14 * * *"

jobs:
  revalidate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Verify required environment variables
        env:
          TMDB_ACCESS_TOKEN: ${{ secrets.TMDB_ACCESS_TOKEN }}
          REVALIDATE_SECRET:   ${{ secrets.REVALIDATE_SECRET }}
          SITE_URL:            ${{ secrets.SITE_URL }}
        run: |
          vars=(TMDB_ACCESS_TOKEN REVALIDATE_SECRET SITE_URL)
          for v in "${vars[@]}"; do
            if [ -z "${!v}" ]; then
              echo "❌ $v is not set"
              exit 1
            else
              echo "✅ $v is set"
            fi
          done

      - name: Run backfill script
        env:
          TMDB_ACCESS_TOKEN: ${{ secrets.TMDB_ACCESS_TOKEN }}
          REVALIDATE_SECRET:   ${{ secrets.REVALIDATE_SECRET }}
          SITE_URL:            ${{ secrets.SITE_URL }}
        run: npm run backfill 
